"""add cognee_seeded to roadmaps

Revision ID: cafaccd3c5ec
Revises: 1bc4c474ba7c
Create Date: 2026-07-03 13:49:04.131121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cafaccd3c5ec'
down_revision: Union[str, None] = '1bc4c474ba7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roadmaps', sa.Column('cognee_seeded', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roadmaps', 'cognee_seeded')
    # ### end Alembic commands ###
